/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.QA;

/**
 *
 * @author Ram
 */
public class GovermentApplication extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public GovermentApplication() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        approveRequestBtn = new javax.swing.JButton();
        declineRequestBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Government Approval UserInterFace");

        approveRequestBtn.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        approveRequestBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/images/check.png"))); // NOI18N
        approveRequestBtn.setText("Approve Funds Request");
        approveRequestBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        approveRequestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approveRequestBtnActionPerformed(evt);
            }
        });

        declineRequestBtn.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        declineRequestBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/images/close.png"))); // NOI18N
        declineRequestBtn.setText("Decline Funds Request");
        declineRequestBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        declineRequestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                declineRequestBtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/approved-600x310_1.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(approveRequestBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(303, 303, 303)
                .addComponent(declineRequestBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 154, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(approveRequestBtn)
                            .addComponent(declineRequestBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(111, 111, 111))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void approveRequestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approveRequestBtnActionPerformed
        //        if(request.getStatus().equalsIgnoreCase("Approved") || request.getStatus().equalsIgnoreCase("Declined")){
            //            JOptionPane.showMessageDialog(null, "The funds have already been Approved/Declined");
            //            return;
            //        }
        //
        //        if(requestedFundFormTextField.getText().equals(""))
        //        {
            //            JOptionPane.showMessageDialog(null, "Please enter a comment!");
            //            return;
            //        }
        //        else{
            //            request.setApproval(requestedFundFormTextField.getText());
            //
            //            final String recipient = request.getSender().toString();//this needs to be an email address
            //            boolean sessionDebug = false;
            //
            //            String from = "taskplannermernproject@gmail.com";
            //            String host = "smtp.gmail.com";
            //            String user="taskplannermernproject@gmail.com";
            //            String pass = "taskplannermernproject@123";
            //            Properties prop = System.getProperties();
            //            prop.setProperty("mail.smtp.host", host);
            //            prop.put("mail.smtp.starttls.required", "true");
            //            prop.put("mail.smtp.starttls.enable", "true");
            //            prop.put("mail.smtp.host", host);
            //            prop.put("mail.smtp.port", "587");
            //            prop.put("mail.smtp.auth", "true");

            //            java.security.Security.addProvider(new com.sun.net.ssl.internal.ssl.Provider());

            //            Session session;
            //            session = Session.getDefaultInstance(prop, null);
            //            session.setDebug(sessionDebug);
            //
            //            try{
                //                MimeMessage msg = new MimeMessage(session);
                //                msg.setFrom(new InternetAddress(from));
                //                msg.setRecipient(Message.RecipientType.TO,new InternetAddress(recipient));
                //                InternetAddress address;
                //                address = new InternetAddress(recipient);
                //                msg.setSubject("Status of the Fund Approval");
                //                msg.setText("The requested fund has been approved");
                //                Transport transport = session.getTransport("smtp");
                //                transport.connect(host,user,pass);
                //                transport.sendMessage(msg, msg.getAllRecipients());
                //                transport.close();
                //            }catch(Exception ex){
                //                JOptionPane.showMessageDialog(null, "Error encountered while sending email");
                //            }
            //
            //            request.setStatus("Approved");
            //            JOptionPane.showMessageDialog(null, "Funds have been approved");
            //        }
    }//GEN-LAST:event_approveRequestBtnActionPerformed

    private void declineRequestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_declineRequestBtnActionPerformed
        // TODO add your handling code here:
        //        if(request.getStatus().equalsIgnoreCase("Approved") || request.getStatus().equalsIgnoreCase("Declined")){
            //            JOptionPane.showMessageDialog(null, "The funds have already been Approved/Declined");
            //            return;
            //        }
        //
        //        if(requestedFundFormTextField.getText().equals(""))
        //        {
            //            JOptionPane.showMessageDialog(null, "Please enter a comment!");
            //            return;
            //        }
        //        else{
            //            request.setApproval(requestedFundFormTextField.getText());
            //
            //            final String recipient = request.getSender().toString();//this needs to be an email address
            //            boolean sessionDebug = false;
            //
            //            String from = "taskplannermernproject@gmail.com";
            //            String host = "smtp.gmail.com";
            //            String user="taskplannermernproject@gmail.com";
            //            String pass = "taskplannermernproject@123";
            //            Properties prop = System.getProperties();
            //            prop.setProperty("mail.smtp.host", host);
            //            prop.put("mail.smtp.starttls.required", "true");
            //            prop.put("mail.smtp.starttls.enable", "true");
            //            prop.put("mail.smtp.host", host);
            //            prop.put("mail.smtp.port", "587");
            //            prop.put("mail.smtp.auth", "true");
            //
            //            //            java.security.Security.addProvider(new com.sun.net.ssl.internal.ssl.Provider());
            //
            //            Session session;
            //            session = Session.getDefaultInstance(prop, null);
            //            session.setDebug(sessionDebug);
            //
            //            try{
                //                MimeMessage msg = new MimeMessage(session);
                //                msg.setFrom(new InternetAddress(from));
                //                msg.setRecipient(Message.RecipientType.TO,new InternetAddress(recipient));
                //                InternetAddress address;
                //                address = new InternetAddress(recipient);
                //                msg.setSubject("Status of the Fund Approval");
                //                msg.setText("The requested fund has been declined");
                //                Transport transport = session.getTransport("smtp");
                //                transport.connect(host,user,pass);
                //                transport.sendMessage(msg, msg.getAllRecipients());
                //                transport.close();
                //            }catch(Exception ex){
                //                JOptionPane.showMessageDialog(null, "Error encountered while sending email");
                //            }
            //
            //            request.setStatus("Declined");
            //            JOptionPane.showMessageDialog(null, "Funds have been declined");
            //        }
    }//GEN-LAST:event_declineRequestBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton approveRequestBtn;
    private javax.swing.JButton declineRequestBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
